# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypto_qt.ui'
#
# Created: Tue Dec 17 02:55:39 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Crypto(object):
    def setupUi(self, Crypto):
        Crypto.setObjectName("Crypto")
        Crypto.resize(441, 442)
        self.centralwidget = QtGui.QWidget(Crypto)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(9999, 9999))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textEdit)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cipherEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cipherEdit.sizePolicy().hasHeightForWidth())
        self.cipherEdit.setSizePolicy(sizePolicy)
        self.cipherEdit.setObjectName("cipherEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cipherEdit)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.keyEdit = QtGui.QLineEdit(self.centralwidget)
        self.keyEdit.setObjectName("keyEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.keyEdit)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodBox.sizePolicy().hasHeightForWidth())
        self.methodBox.setSizePolicy(sizePolicy)
        self.methodBox.setMinimumSize(QtCore.QSize(98, 0))
        self.methodBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.methodBox.setObjectName("methodBox")
        self.horizontalLayout.addWidget(self.methodBox)
        self.encryptButton = QtGui.QPushButton(self.centralwidget)
        self.encryptButton.setObjectName("encryptButton")
        self.horizontalLayout.addWidget(self.encryptButton)
        self.decryptButton = QtGui.QPushButton(self.centralwidget)
        self.decryptButton.setObjectName("decryptButton")
        self.horizontalLayout.addWidget(self.decryptButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Crypto.setCentralWidget(self.centralwidget)

        self.retranslateUi(Crypto)
        QtCore.QMetaObject.connectSlotsByName(Crypto)

    def retranslateUi(self, Crypto):
        Crypto.setWindowTitle(QtGui.QApplication.translate("Crypto", "Crypto-qt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Crypto", "Cipher: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Crypto", "Key: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Crypto", "Text: ", None, QtGui.QApplication.UnicodeUTF8))
        self.encryptButton.setText(QtGui.QApplication.translate("Crypto", "Encrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.decryptButton.setText(QtGui.QApplication.translate("Crypto", "Decrypt", None, QtGui.QApplication.UnicodeUTF8))

